# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



- script: |
    mkdir -p ~/.ssh
    ssh-keyscan 193.122.191.76 >> ~/.ssh/known_hosts
  displayName: 'Add remote host key to known_hosts'

- script: |
    cat ~/.ssh/known_hosts
  displayName: 'Display known_hosts'